if (YOCTO) 
  set(VCPKG_ROOT /usr)
  set(VCPKG_TOOLS /usr)
  set(CURL_LIB curl)
  set(EXTRA_LIBRARIES ssl crypto pthread dl z)
  set(MQTT_LIB mosquitto)
else()
  if (WIN32)
    set(VCPKG_DIR c:/usr/vcpkg)
    set(VCPKG_ROOT ${VCPKG_DIR}/installed/x64-windows)
    set(VCPKG_TOOLS ${VCPKG_ROOT}/tools)
    set(CURL_LIB libcurl)
    set(EXTRA_LIBRARIES libcrypto libssl)
    set(MQTT_LIB mosquitto)
  else()
    set(CURL_LIB curl)
    set(EXTRA_LIBRARIES ssl crypto pthread dl fmt uv z)
    #set(MQTT_LIB mosquitto_static)
    set(MQTT_LIB paho-mqtt3c)
  endif()
  include_directories(${VCPKG_ROOT}/include)
  link_directories(BEFORE ${VCPKG_ROOT}/lib)
endif()
