if (YOCTO) 
  set(VCPKG_ROOT /usr)
  set(CURL_LIB curl)
  set(EXTRA_LIBRARIES ssl crypto pthread dl z)
  set(MOSQUITTO_LIB mosquitto)
else()
  if (WIN32)
    set(VCPKG_DIR c:/usr/vcpkg)
    set(VCPKG_ROOT ${VCPKG_DIR}/installed/x64-windows)
    set(CURL_LIB libcurl)
    set(EXTRA_LIBRARIES libcrypto libssl)
    set(MOSQUITTO_LIB mosquitto)
  else()
    set(VCPKG_DIR /home/jari/vcpkg)
    set(VCPKG_ROOT ${VCPKG_DIR}/installed/x64-linux)
    set(CURL_LIB curl)
    set(EXTRA_LIBRARIES ssl crypto pthread dl z)
    set(MOSQUITTO_LIB mosquitto_static)
  endif()
  set(CMAKE_TOOLCHAIN_FILE ${VCPKG_DIR}/scripts/buildsystems/vcpkg.cmake)
endif()
