FROM debian:12-slim

# Install necessary packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    g++-aarch64-linux-gnu \
    gdb \
    cmake \
    make \
    git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV VCPKG_ROOT=/vcpkg

VOLUME /vcpkg
VOLUME /workspace

CMD ["/bin/bash"]