@startuml C4 context
!include ./C4_Context.puml
!include https://raw.githubusercontent.com/patrik-csak/one-dark-plantuml-theme/v1.0.1/theme.puml

'LAYOUT_WITH_LEGEND()

System_Ext(mqtt, "Mosquitto", "MQTT broker")
System_Ext(z2m, "zigbee2mqtt", "zigbee2mqtt")
System_Ext(nodered, "NodeRed", "App")
Person_Ext(user, "Configuration", "User")
System(yaha, "Yaha", "C++ app")
System(weather, "Weather", "C++ app")
System(spot, "Spot", "C++ app")
SystemDb(db, "sqlite DB", "DB", "data")
System_Ext(fmi, "Weather API", "API")
System_Ext(nordpool, "Price API", "API")

Rel_L(nodered, mqtt, "messages")
BiRel_R(z2m, mqtt, "messages")
BiRel_D(mqtt, yaha, "messages")
BiRel_D(mqtt, weather, "messages")
BiRel_D(mqtt, spot, "messages")
Rel_D(yaha, db, "database")
Rel_D(user, z2m, "Web UI")
Rel_D(user, nodered, "Web UI")
Rel_D(weather, fmi, "http")
Rel_D(spot, nordpool, "http")
BiRel_D(weather, db, "sql")
BiRel_D(spot, db, "sql")

@enduml
